CREATE TABLE public.members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_code varchar(50) NOT NULL,
    github_user_hash varchar(50) NOT NULL,
    linkedin_user_hash varchar(50),
    created_at timestamptz DEFAULT now() NOT NULL
);