CREATE TABLE public.metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value varchar(10) not null,
    symbol varchar(1) null,
    created_at timestamptz DEFAULT now() NOT NULL
);
