CREATE TABLE public.member_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.members
ADD member_role_id bigint NULL,
ADD CONSTRAINT fk_member_role
    FOREIGN KEY (member_role_id)
    REFERENCES public.member_roles(id);