CREATE TABLE public.member_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL,
    name varchar(250) NOT NULL,
    last_name varchar(250) NOT NULL,
    position varchar(250) NOT NULL,
    skills varchar(250) NOT NULL,
    summary text NOT NULL,
    lang varchar(5) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    
    CONSTRAINT member_translations_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);